/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CalendarItems {
  data: string | null;
  end_time: number;
  id: string | null;
  owner_id: string;
  start_time: number;
  type: string;
}

export interface Drills {
  duration_seconds: number | null;
  id: string | null;
  skill_id: string;
}

export interface DrillSessions {
  completed_at: number | null;
  drill_id: string;
  feedback: string | null;
  id: string | null;
  started_at: number;
  success: Generated<number | null>;
  user_id: string;
}

export interface Entities {
  created_at: number;
  data: string;
  id: string | null;
  type: string;
  updated_at: number;
}

export interface HabitInstances {
  completed: Generated<number | null>;
  id: string | null;
  scheduled_date: number;
  streak: Generated<number | null>;
  template_id: string;
}

export interface HabitTemplates {
  default_duration_minutes: number | null;
  default_priority: number | null;
  description: string | null;
  id: string | null;
  image_id: string | null;
  name: string;
  tags: string | null;
}

export interface HealthMetricsDaily {
  anxiety: number | null;
  date: string;
  id: string | null;
  recovery_pct: number | null;
  social_anxiety: number | null;
  social_initiative: number | null;
  stress: number | null;
  user_id: string;
}

export interface Images {
  created_at: number;
  entity_id: string;
  id: string | null;
  image_url: string;
}

export interface ObjectiveLinks {
  child_id: string;
  parent_id: string;
}

export interface Objectives {
  due_date: number | null;
  id: string | null;
  is_active: Generated<number | null>;
  parent_id: string | null;
  progress: Generated<number | null>;
  sort_order: Generated<number | null>;
}

export interface Reflections {
  data: string;
  id: string | null;
  timestamp: number;
  type: string;
  user_id: string;
}

export interface RewardRedemptions {
  id: string | null;
  points_spent: number | null;
  redeemed_at: number;
  reward_id: string;
  user_id: string;
}

export interface Rewards {
  color: string | null;
  description: string | null;
  effort_required: number | null;
  id: string | null;
  image_id: string | null;
  is_favorite: Generated<number | null>;
  name: string;
  tags: string | null;
  url: string | null;
}

export interface Skills {
  anxiety_required: number | null;
  id: string | null;
  mastery: Generated<number | null>;
  name: string;
  type: string | null;
}

export interface SocialBattery {
  current_level: number;
  id: string | null;
  last_updated: number;
  recovery_rate: number | null;
}

export interface SupportContacts {
  email: string | null;
  escalation_level: number | null;
  id: string | null;
  name: string;
  phone: string | null;
  relation: string | null;
  user_id: string;
}

export interface TimeSeries {
  context: string | null;
  entity_id: string;
  metric_name: string;
  timestamp: number;
  value: number;
}

export interface DB {
  calendar_items: CalendarItems;
  drill_sessions: DrillSessions;
  drills: Drills;
  entities: Entities;
  habit_instances: HabitInstances;
  habit_templates: HabitTemplates;
  health_metrics_daily: HealthMetricsDaily;
  images: Images;
  objective_links: ObjectiveLinks;
  objectives: Objectives;
  reflections: Reflections;
  reward_redemptions: RewardRedemptions;
  rewards: Rewards;
  skills: Skills;
  social_battery: SocialBattery;
  support_contacts: SupportContacts;
  time_series: TimeSeries;
}
